### ISSUE TITLE
Add instructions on how to install Ansible

### ISSUE THREAD

**Issue by cbolz** [ansible-labs-crew/ansible-labs-summit2021#19]
the deployer does not install Ansible on the bastion host - we need to add instructions for the student to it themselves.

```
sudo yum -y install ansible
```

This has to be double checked and added to all applicable labs.

**Comment by ericzolf** [comment]
Ansible is installed in a virtualenv under `/opt`, it doesn't need to be installed again IMHO.

**Comment by goetzrieger** [comment]
I don't think we want to explain running Ansible in a venv...

**Comment by goetzrieger** [comment]
Because than we would have to use an Execution Environment instead... LOL

**Comment by cbolz** [comment]
IMHO it does, since using a venv is just extra trouble - also the venv will always install the latest version of ansible, which can potentially add new features which we do not explain or cover in the lab guide

**Comment by goetzrieger** [comment]
Okay 2:1, we instruct to install Ansible.

**Comment by cbolz** [comment]
closed by merging https://github.com/ansible-labs-crew/ansible-labs-summit2021/pull/21

**Comment by ericzolf** [comment]
Well, I don't agree but whatever: it's the Ansible we use for our automation so it can't be too exotic, and calling `/opt/..../ansible` isn't much hassle.
